trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadSecureFile@1
  displayName: 'Download secure file for pipelines to access gcp'
  inputs:
    secureFile: 'azure-gcp.json'

- task: DownloadSecureFile@1
  displayName: 'Download config file'
  inputs:
    secureFile: ecn_viewer_config.json

- script: |
    echo "deb https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
    sudo apt-get update && sudo apt-get install google-cloud-sdk

    gcloud --quiet auth activate-service-account --key-file=$(Agent.TempDirectory)/azure-gcp.json
    gcloud --quiet config set project focal-freedom-236620

    # set env var GOOGLE_APPLICATION_CREDENTIALS for terraform to pick up for GCP authentication
    echo "##vso[task.setvariable variable=GOOGLE_APPLICATION_CREDENTIALS]$(Agent.TempDirectory)/azure-gcp.json"
  displayName: 'Install and init gcloud'

- task: TerraformInstaller@0
  inputs:
    terraformVersion: '0.11.14'

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    cp $(Agent.TempDirectory)/ecn_viewer_config.json $(System.DefaultWorkingDirectory)/src/ControllerProvider/controller.json
    npm install
    npm run build
  displayName: 'npm install and build'

- script: |
    ssh-keygen -b 2048 -t rsa -f /tmp/sshkey -q -N ""

- script: |
    terraform init
  displayName: 'Init terraform'
  workingDirectory: $(System.DefaultWorkingDirectory)/infrastructure

- script: |
    terraform destroy -auto-approve \
    -var 'gce_ssh_private_key_file=/tmp/sshkey' \
    -var 'gce_ssh_pub_key_file=/tmp/sshkey.pub' \
  displayName: 'destroy'
  workingDirectory: $(System.DefaultWorkingDirectory)/infrastructure

- script: |
    terraform apply -auto-approve \
    -var 'gce_ssh_private_key_file=/tmp/sshkey' \
    -var 'gce_ssh_pub_key_file=/tmp/sshkey.pub' \
  displayName: 'spin up instance '
  workingDirectory: $(System.DefaultWorkingDirectory)/infrastructure